wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    code_path: code/train.py
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.2
    t:
      1:
      - 5
      4: 3.7.2
      5: 0.10.27
      8:
      - 5
config_key:
  desc: null
  value: tav
