wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.2
    t:
      4: 3.7.2
      5: 0.10.28
      8:
      - 5
